<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="3.0" xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:hei="https://digi.ub.uni-heidelberg.de/schema/tei/heiEDITIONS"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xsl:output method="xml"/>

    <xsl:mode on-no-match="shallow-copy"/>


    <xsl:template match="teiHeader">
        <xsl:copy>
            <xsl:apply-templates/>

            <xsl:if test="not(revisionDesc)">
                <revisionDesc>
                    <listChange>
                        <xsl:call-template name="insertChange"/>
                    </listChange>
                </revisionDesc>
            </xsl:if>
        </xsl:copy>
    </xsl:template>


    <xsl:template match="revisionDesc">
        <xsl:copy>
            <xsl:apply-templates/>
            <xsl:if test="not(listChange)">
                <listChange>
                    <xsl:call-template name="insertChange"/>
                </listChange>
            </xsl:if>
        </xsl:copy>
    </xsl:template>


    <xsl:template match="revisionDesc/listChange">
        <xsl:copy>
            <xsl:apply-templates/>
            <xsl:call-template name="insertChange"/>
        </xsl:copy>
    </xsl:template>


    <xsl:template name="insertChange">
        <change when="{format-date(current-date(), '[Y0001]-[M01]-[D01]')}">This has been generated by heipy</change>
    </xsl:template>


</xsl:stylesheet>
